fix ChangeVision/stpa-proto/#3285 ASY プラグイン SDKの利用ガイドを作成する
ChangeVision/astah-plugin-tutorial-ja pull request #7
Opened 2021-08-03 07:53 UTC by y-zhou

https://github.com/ChangeVision/stpa-proto/issues/3285

2021-09-02 02:43 UTC, aasakawa requested changes
@y-zhou 念の為の確認ですが、 ASY の SDK で実際にチュートリアルが動作するかは確認済みですか？

2021-09-02 02:43 UTC, aasakawa commented on source/apilist.rst
> + * `astah* SysML API利用ガイド <https://astah.change-vision.com/ja/tutorial/api-sysml.html>`_
Scheme だけでなく Path も変わっていますが、大丈夫でしょうか？

2021-09-02 02:43 UTC, aasakawa commented on source/index.rst
>  IntelliJ IDEA         11.1
(Cc @kamura) 各種バージョンが古すぎる気がしますが、大丈夫でしょうか？

2021-09-02 02:43 UTC, aasakawa commented on source/apilist.rst
> + * `astah* System Safety API JavaDoc <https://members.change-vision.com/javadoc/asy-api/6_0_0/ja/doc/javadoc/index.html>`_
(Cc @kamura ) バージョン指定は避けたいはずですが、このままで良いのでしょうか？

2021-09-02 02:43 UTC, aasakawa commented on build/html/_sources/releaseplugin.rst.txt
> +think              think
ASY の記載が漏れています。
(Cc @kamura ) また、 ASY では ChangeVision/sysml#1991 で複数のエディション互換としたので、その記述もあった方が良いと感じます。

2021-09-06 02:36 UTC, y-zhou commented on source/apilist.rst
> + * `astah* SysML API利用ガイド <https://astah.change-vision.com/ja/tutorial/api-sysml.html>`_
@aasakawa 
ASY の SDKですが、中谷さんのタスクで作成したSDKを用いて、利用ガイドを参考に動かしてみましたが、それで十分でしょうか？
利用法は、従来のSDKと変わりがないと思っていました。

生成した各htmlから各リンク先ページを開けるという確認はしましたが、ほかの何かが必要でしょうか？

2021-09-06 02:37 UTC, y-zhou commented on source/index.rst
>  IntelliJ IDEA         11.1
@aasakawa  @kamura

各種のバージョンをどうしましょうか？
決めて頂けませんか？

2021-09-06 02:40 UTC, y-zhou commented on source/apilist.rst
> + * `astah* System Safety API JavaDoc <https://members.change-vision.com/javadoc/asy-api/6_0_0/ja/doc/javadoc/index.html>`_
@aasakawa @kamura 
公開しているAPI利用ガイドのリンクを見ると,バージョン指定となっていますね！
無くすなら、三竹さん?に連絡し、こちらも修正します。どうしましょう？

2021-09-07 00:28 UTC, y-zhou commented on source/index.rst
>  IntelliJ IDEA         11.1
@kamura @aasakawa 
OSにASYはLinuxのサポートなし。いったん

2021-09-07 00:32 UTC, y-zhou commented on build/html/_sources/releaseplugin.rst.txt
> +think              think
ProfessionalとUMLの下に記述する

2021-09-08 22:57 UTC, aasakawa requested changes

2021-09-08 22:57 UTC, aasakawa commented on source/apilist.rst
> + * `astah* SysML API利用ガイド <https://astah.change-vision.com/ja/tutorial/api-sysml.html>`_
旧: `http://astah.change-vision.com/ja/feature/astah-sysml-api-user-guide.html`
新: `https://astah.change-vision.com/ja/tutorial/api-sysml.html`

と変わっていますが、 `feature/astah-sysml-api-user-guide.html` を `tutorial/api-sysml.html` を変える理由があったのですか？今回 Pro/SysML に関しては `http://` から `https://` に変えただけなのでは？

2021-09-08 22:57 UTC, aasakawa commented on source/releaseplugin.rst
> +System Safety      safety
ChangeVision/sysml#1991 を確認して下さい。

`safety、または SystemSafety` と書くべきです。

あと、

> また、 ASY では ChangeVision/sysml#1991 で複数のエディション互換としたので、その記述もあった方が良いと感じます。

の部分はどうなったのでしょうか？

2021-09-09 05:47 UTC, y-zhou commented on source/releaseplugin.rst
> +System Safety      safety
@aasakawa 
 `feature/astah-sysml-api-user-guide.html` を `tutorial/api-sysml.html` に変えたのは、`feature/astah-sysml-api-user-guide.html`のリンク切れでした。上馬さんと話して、今の`tutorial/api-sysml.html`に変えました。

2021-09-09 05:55 UTC, aasakawa requested changes

2021-09-09 05:55 UTC, aasakawa commented on source/releaseplugin.rst
> +System Safety      safety またはSystemSafety ( pro8.4互換, uml8.4互換, sysml1.1互換)
この書き方だと対象バージョンを修正する度にチュートリアルの書き換えが必要になってしまいます。

`(互換バージョンを対象とする場合はpro/UML/SysML向けも動作します)`

として下さい。

2021-09-09 06:46 UTC, aasakawa requested changes

2021-09-09 06:46 UTC, aasakawa commented on source/index.rst
> +astah*                6.8(Professional, UML, Community),1.1(SysML),Safety System(6.0)
ここともう一箇所が `Safety System` になってしまっています。

2021-09-09 08:15 UTC, aasakawa approved these changes

2021-09-09 08:15 UTC, merged